pluginManagement {
    repositories {
        gradlePluginPortal()
        google()
        mavenCentral()
    }
}

dependencyResolutionManagement {
    repositoriesMode.set(RepositoriesMode.FAIL_ON_PROJECT_REPOS)
    repositories {
        google()
        mavenCentral()
        maven { url "https://android-sdk.is.com" }
    }

    repositories {
        maven {
            url = "https://maven.pkg.github.com/tungtbz/extralibs"
            credentials {
                username = providers.gradleProperty("GITHUB_USER_NAME").getOrElse("")
                password = providers.gradleProperty("GITHUB_TOKEN").getOrElse("")
            }
        }
    }
}

rootProject.name = "AdsModule_Native"
include ':app'
include ':base'
include ':maxads'
include ':remoteconfig'
include ':analytic'
include ':ads'
include ':ironsourceads'
include ':nativeads'
include ':admobadshelper'
include ':admobadshelper'
include ':camerapreview'
