plugins {
    id 'com.android.library'
    id 'maven-publish'
}

// Place the version of your library here
def getVersionName = { ->
    return "0.0.1"
}
// Add the name of your library here
def getArtifactId = { ->
    return "max-ads"
}

// Add the group ID of your library here
def getGroupId = { ->
    return "com.tungt"
}

def getGitHubUrl = { ->
    return "https://maven.pkg.github.com/tungtbz/max-asd"
}

publishing {
    publications {
        bar(MavenPublication) {
            groupId getGroupId()
            artifactId getArtifactId()
            version getVersionName()
            // Place the path of your artifact here
            artifact("build/outputs/aar/${getArtifactId()}.jar")
        }
    }
    repositories {
        maven {
            name = "GitHubPackages"

            url = uri(getGitHubUrl())
            credentials {
                username = GITHUB_USER_NAME
                password = GITHUB_TOKEN_PUSH
            }
        }
    }
}

android {
    compileSdk 33

    defaultConfig {
        minSdk 21
        targetSdk 33

        testInstrumentationRunner "androidx.test.runner.AndroidJUnitRunner"
        consumerProguardFiles "consumer-rules.pro"
    }

    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
    }
    compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    }
}

dependencies {
    implementation 'com.applovin:applovin-sdk:+'
    implementation 'com.applovin.mediation:amazon-tam-adapter:+'
    implementation 'com.amazon.android:aps-sdk:+'
    implementation 'androidx.appcompat:appcompat:1.6.1'
    implementation project(':base')
    implementation project(':remoteconfig')
    implementation project(':ads')
    implementation 'com.tungt:unity-classes:0.0.1'
}